name: Build and Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            asset_name: aimit-linux-x86_64
          # # Linux ARM64
          # - target: aarch64-unknown-linux-gnu
          #   os: ubuntu-latest
          #   asset_name: aimit-linux-aarch64
          # macOS x86_64 (Intel)
          - target: x86_64-apple-darwin
            os: macos-latest
            asset_name: aimit-macos-x86_64
          # macOS ARM64 (Apple Silicon)
          - target: aarch64-apple-darwin
            os: macos-latest
            asset_name: aimit-macos-aarch64
          # Windows x86_64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            asset_name: aimit-windows-x86_64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install musl-tools (for Linux musl builds)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: target/${{ matrix.target }}/release/aimit${{ matrix.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create release archive
        run: |
          mkdir -p release-binaries
          for artifact_dir in */; do
            artifact_name=$(basename "$artifact_dir")
            echo "Processing artifact: $artifact_name"
            if [[ "$artifact_name" == *"windows"* ]]; then
              # Find the .exe file and copy it with a unique name
              exe_file=$(find "$artifact_dir" -name "*.exe" -type f | head -1)
              if [[ -n "$exe_file" ]]; then
                cp "$exe_file" "release-binaries/$artifact_name.exe"
                echo "Copied Windows binary: $exe_file -> release-binaries/$artifact_name.exe"
              fi
            else
              # Find the binary file and copy it with a unique name
              binary_file=$(find "$artifact_dir" -type f -executable | head -1)
              if [[ -n "$binary_file" ]]; then
                cp "$binary_file" "release-binaries/$artifact_name"
                echo "Copied binary: $binary_file -> release-binaries/$artifact_name"
              fi
            fi
          done

          # List what we have
          echo "Files in release-binaries:"
          ls -la release-binaries/

          # Create a zip file with all binaries
          cd release-binaries
          zip -r ../aimit-binaries.zip .
          cd ..

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./aimit-binaries.zip
          asset_name: aimit-binaries.zip
          asset_content_type: application/zip

  update-binaries:
    name: Update Binary Files
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Prepare binaries for bin directory
        run: |
          mkdir -p bin
          
          # Remove old generic binary files if they exist (migration to platform-specific names)
          if [[ -f "bin/aimit" ]]; then
            echo "Removing old generic binary: bin/aimit"
            rm "bin/aimit"
          fi
          if [[ -f "bin/aimit.exe" ]]; then
            echo "Removing old generic binary: bin/aimit.exe"
            rm "bin/aimit.exe"
          fi
          
          # Debug: List all artifact directories
          echo "Artifact directories:"
          ls -la */
          
          for artifact_dir in */; do
            artifact_name=$(basename "$artifact_dir")
            
            # Only process directories that start with 'aimit-' (actual artifacts)
            # Skip workspace directories like bin/, src/, target/, etc.
            if [[ ! "$artifact_name" =~ ^aimit- ]]; then
              echo "Skipping non-artifact directory: $artifact_name"
              continue
            fi
            
            echo "Processing artifact: $artifact_name"

            echo "Contents of $artifact_dir:"
            ls -la "$artifact_dir" || true
            
            if [[ "$artifact_name" == *"windows"* ]]; then
              # Find the .exe file and copy it with platform-specific name
              exe_file=$(find "$artifact_dir" -name "*.exe" -type f | head -1)
              if [[ -n "$exe_file" ]]; then
                cp "$exe_file" "bin/$artifact_name"
                echo "Copied Windows binary: $exe_file -> bin/$artifact_name"
              else
                echo "WARNING: No .exe file found in $artifact_dir"
              fi
            else
              # Find any binary file (try multiple methods)
              # First try to find a file named 'aimit' (limit depth to avoid source code)
              binary_file=$(find "$artifact_dir" -maxdepth 2 -name "aimit" -type f | head -1)

              # If not found, try finding files in root of artifact directory only
              # Exclude source code files and hidden files
              if [[ -z "$binary_file" ]]; then
                binary_file=$(find "$artifact_dir" -maxdepth 1 -type f ! -name ".*" ! -name "*.rs" ! -name "*.toml" ! -name "*.json" ! -name "*.md" ! -name "*.txt" ! -name "*.yml" ! -name "*.yaml" ! -name "*.sh" | head -1)
              fi

              # If still not found, try with executable permission and depth limit
              if [[ -z "$binary_file" ]]; then
                binary_file=$(find "$artifact_dir" -maxdepth 2 -type f -executable ! -name "*.rs" ! -name "*.toml" ! -name "*.json" | head -1)
              fi

              if [[ -n "$binary_file" ]]; then
                cp "$binary_file" "bin/$artifact_name"
                chmod +x "bin/$artifact_name"
                echo "Copied binary: $binary_file -> bin/$artifact_name"
              else
                echo "WARNING: No binary file found in $artifact_dir"
              fi
            fi
          done

          # List what we have
          echo "Files in bin directory:"
          ls -la bin/

      - name: Commit and push binaries
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add bin/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update binaries for release ${{ github.sha }}"
            git push
          fi
